server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/booking
    user: dev
    password: dev
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: BOOKING-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8080/eureka
